import {
  User,
  Property,
  TenancyAgreement,
  Dispute,
  RentAdjustment,
  PricingStrategy,
  Notification,
  AnalyticsData,
  RentPayment,
  SupportingDocument,
  AuditLog,
  PenaltyNotice,
  SystemParameter,
} from './types';

export const currentUser: User = {
  id: 'u1',
  firstName: 'Yohannes',
  lastName: 'Mesay',
  email: 'yohannes@example.com',
  phone: '+251911234567',
  role: 'admin',
  createdAt: '2025-01-15',
  isVerified: true,
  address: 'Bole Sub-City, Woreda 03',
  idNumber: 'AA-2025-00001',
};

export const users: User[] = [
  currentUser,
  {
    id: 'u2',
    firstName: 'Abebe',
    lastName: 'Kebede',
    email: 'abebe.k@example.com',
    phone: '+251922345678',
    role: 'landlord',
    createdAt: '2025-02-10',
    isVerified: true,
    address: 'Kirkos Sub-City, Woreda 07',
    idNumber: 'AA-2025-00042',
  },
  {
    id: 'u3',
    firstName: 'Tigist',
    lastName: 'Haile',
    email: 'tigist.h@example.com',
    phone: '+251933456789',
    role: 'tenant',
    createdAt: '2025-03-05',
    isVerified: true,
    address: 'Yeka Sub-City, Woreda 12',
    idNumber: 'AA-2025-00078',
  },
  {
    id: 'u4',
    firstName: 'Dawit',
    lastName: 'Tadesse',
    email: 'dawit.t@example.com',
    phone: '+251944567890',
    role: 'landlord',
    createdAt: '2025-01-20',
    isVerified: true,
    address: 'Bole Sub-City, Woreda 05',
    idNumber: 'AA-2025-00103',
  },
  {
    id: 'u5',
    firstName: 'Sara',
    lastName: 'Getachew',
    email: 'sara.g@example.com',
    phone: '+251955678901',
    role: 'tenant',
    createdAt: '2025-04-12',
    isVerified: true,
    address: 'Lideta Sub-City, Woreda 02',
    idNumber: 'AA-2025-00155',
  },
  {
    id: 'u6',
    firstName: 'Mulugeta',
    lastName: 'Assefa',
    email: 'mulugeta.a@example.com',
    phone: '+251966789012',
    role: 'dara_agent',
    createdAt: '2025-01-05',
    isVerified: true,
    address: 'Arada Sub-City, Woreda 01',
    idNumber: 'AUTH-2025-001',
  },
  {
    id: 'u7',
    firstName: 'Helen',
    lastName: 'Worku',
    email: 'helen.w@example.com',
    phone: '+251977890123',
    role: 'tenant',
    createdAt: '2025-05-01',
    isVerified: false,
    address: 'Nifas Silk-Lafto Sub-City, Woreda 04',
    idNumber: 'AA-2025-00201',
  },
  {
    id: 'u8',
    firstName: 'Bereket',
    lastName: 'Solomon',
    email: 'bereket.s@example.com',
    phone: '+251988901234',
    role: 'landlord',
    createdAt: '2025-02-28',
    isVerified: true,
    address: 'Gullele Sub-City, Woreda 06',
    idNumber: 'AA-2025-00250',
  },
  {
    id: 'u9',
    firstName: 'Meron',
    lastName: 'Tadesse',
    email: 'meron.t@example.com',
    phone: '+251911001234',
    role: 'tenant',
    createdAt: '2025-06-10',
    isVerified: true,
    address: 'Kolfe Keranio Sub-City, Woreda 09',
    idNumber: 'AA-2025-00312',
  },
  {
    id: 'u10',
    firstName: 'Kidist',
    lastName: 'Alemu',
    email: 'kidist.a@example.com',
    phone: '+251922101234',
    role: 'admin',
    createdAt: '2025-01-01',
    isVerified: true,
    address: 'Arada Sub-City, Woreda 03',
    idNumber: 'GOV-2025-005',
  },
];

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'Modern 2BR Apartment in Bole',
    address: 'Bole Atlas, Near Edna Mall',
    subCity: 'Bole',
    woreda: '03',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    amenities: ['Parking', 'Guard/Security', 'Water Tank', 'Elevator'],
    monthlyRent: 15000,
    status: 'rented',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    images: [],
    description: 'A modern apartment in the heart of Bole with great amenities and easy access to transportation.',
    createdAt: '2025-02-15',
    verifiedAt: '2025-02-20',
  },
  {
    id: 'p2',
    title: 'Spacious 3BR House in Yeka',
    address: 'Megenagna Area, Behind Yeka Mall',
    subCity: 'Yeka',
    woreda: '12',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    amenities: ['Parking', 'Guard/Security', 'Garden', 'Water Tank', 'Generator'],
    monthlyRent: 25000,
    status: 'available',
    landlordId: 'u4',
    landlordName: 'Dawit Tadesse',
    images: [],
    description: 'Spacious family home with a private garden and secure parking. Located in a quiet residential area.',
    createdAt: '2025-03-10',
    verifiedAt: '2025-03-15',
  },
  {
    id: 'p3',
    title: 'Studio Condominium in Kirkos',
    address: 'Kazanchis, Near Dembel City Center',
    subCity: 'Kirkos',
    woreda: '07',
    propertyType: 'condominium',
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    amenities: ['Parking', 'Guard/Security', 'Elevator', 'Internet'],
    monthlyRent: 8000,
    status: 'rented',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    images: [],
    description: 'Cozy studio apartment perfect for young professionals. Walking distance to major business centers.',
    createdAt: '2025-01-20',
    verifiedAt: '2025-01-25',
  },
  {
    id: 'p4',
    title: 'Luxury Villa in CMC',
    address: 'CMC Area, Michael Road',
    subCity: 'Yeka',
    woreda: '14',
    propertyType: 'villa',
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    amenities: ['Parking', 'Guard/Security', 'Garden', 'Water Tank', 'Generator', 'Furnished', 'Satellite TV'],
    monthlyRent: 55000,
    status: 'verified',
    landlordId: 'u8',
    landlordName: 'Bereket Solomon',
    images: [],
    description: 'A luxurious fully furnished villa with beautiful garden and top-tier amenities.',
    createdAt: '2025-04-01',
    verifiedAt: '2025-04-10',
  },
  {
    id: 'p5',
    title: '2BR Apartment in Nifas Silk',
    address: 'Gotera Area, Nifas Silk',
    subCity: 'Nifas Silk-Lafto',
    woreda: '04',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    area: 72,
    amenities: ['Parking', 'Water Tank', 'Balcony'],
    monthlyRent: 12000,
    status: 'pending_verification',
    landlordId: 'u4',
    landlordName: 'Dawit Tadesse',
    images: [],
    description: 'Affordable apartment with a nice balcony and natural light. Close to public transport.',
    createdAt: '2025-05-20',
  },
  {
    id: 'p6',
    title: '1BR Condominium in Lideta',
    address: 'Lideta Area, Near Stadium',
    subCity: 'Lideta',
    woreda: '02',
    propertyType: 'condominium',
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    amenities: ['Parking', 'Guard/Security', 'Elevator'],
    monthlyRent: 9500,
    status: 'available',
    landlordId: 'u8',
    landlordName: 'Bereket Solomon',
    images: [],
    description: 'Well-maintained condominium in a central location. Ideal for singles and couples.',
    createdAt: '2025-03-28',
    verifiedAt: '2025-04-02',
  },
  {
    id: 'p7',
    title: '3BR House in Gullele',
    address: 'Shiro Meda, Gullele',
    subCity: 'Gullele',
    woreda: '06',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    area: 130,
    amenities: ['Parking', 'Garden', 'Water Tank', 'Storage Room'],
    monthlyRent: 18000,
    status: 'rented',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    images: [],
    description: 'Family-friendly house in a peaceful neighborhood with ample parking and storage.',
    createdAt: '2025-02-05',
    verifiedAt: '2025-02-12',
  },
  {
    id: 'p8',
    title: 'Penthouse Apartment in Bole',
    address: 'Bole Medhanealem, Skylight Area',
    subCity: 'Bole',
    woreda: '08',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    amenities: ['Parking', 'Guard/Security', 'Elevator', 'Furnished', 'Internet', 'Balcony', 'Generator'],
    monthlyRent: 45000,
    status: 'rejected',
    landlordId: 'u4',
    landlordName: 'Dawit Tadesse',
    images: [],
    description: 'Premium penthouse with panoramic city views. Document verification failed.',
    createdAt: '2025-04-15',
  },
];

export const agreements: TenancyAgreement[] = [
  {
    id: 'a1',
    propertyId: 'p1',
    propertyTitle: 'Modern 2BR Apartment in Bole',
    propertyAddress: 'Bole Atlas, Near Edna Mall',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    tenantId: 'u3',
    tenantName: 'Tigist Haile',
    monthlyRent: 15000,
    advancePayment: 30000,
    startDate: '2025-03-01',
    endDate: '2027-02-28',
    status: 'active',
    createdAt: '2025-02-20',
    signedAt: '2025-02-25',
    verifiedAt: '2025-02-28',
    utilities: ['Water', 'Electricity (shared)'],
  },
  {
    id: 'a2',
    propertyId: 'p3',
    propertyTitle: 'Studio Condominium in Kirkos',
    propertyAddress: 'Kazanchis, Near Dembel City Center',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    tenantId: 'u5',
    tenantName: 'Sara Getachew',
    monthlyRent: 8000,
    advancePayment: 16000,
    startDate: '2025-04-01',
    endDate: '2027-03-31',
    status: 'active',
    createdAt: '2025-03-15',
    signedAt: '2025-03-20',
    verifiedAt: '2025-03-25',
    utilities: ['Water', 'Internet'],
  },
  {
    id: 'a3',
    propertyId: 'p7',
    propertyTitle: '3BR House in Gullele',
    propertyAddress: 'Shiro Meda, Gullele',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    tenantId: 'u9',
    tenantName: 'Meron Tadesse',
    monthlyRent: 18000,
    advancePayment: 36000,
    startDate: '2025-03-15',
    endDate: '2027-03-14',
    status: 'active',
    createdAt: '2025-03-01',
    signedAt: '2025-03-10',
    verifiedAt: '2025-03-14',
    utilities: ['Water'],
  },
  {
    id: 'a4',
    propertyId: 'p2',
    propertyTitle: 'Spacious 3BR House in Yeka',
    propertyAddress: 'Megenagna Area, Behind Yeka Mall',
    landlordId: 'u4',
    landlordName: 'Dawit Tadesse',
    tenantId: 'u7',
    tenantName: 'Helen Worku',
    monthlyRent: 25000,
    advancePayment: 50000,
    startDate: '2025-06-01',
    endDate: '2027-05-31',
    status: 'pending_tenant_signature',
    createdAt: '2025-05-15',
    utilities: ['Water', 'Electricity'],
  },
  {
    id: 'a5',
    propertyId: 'p6',
    propertyTitle: '1BR Condominium in Lideta',
    propertyAddress: 'Lideta Area, Near Stadium',
    landlordId: 'u8',
    landlordName: 'Bereket Solomon',
    tenantId: 'u3',
    tenantName: 'Tigist Haile',
    monthlyRent: 9500,
    advancePayment: 19000,
    startDate: '2025-07-01',
    endDate: '2027-06-30',
    status: 'pending_verification',
    createdAt: '2025-06-01',
    signedAt: '2025-06-05',
    utilities: ['Water', 'Guard service'],
  },
  {
    id: 'a6',
    propertyId: 'p4',
    propertyTitle: 'Luxury Villa in CMC',
    propertyAddress: 'CMC Area, Michael Road',
    landlordId: 'u8',
    landlordName: 'Bereket Solomon',
    tenantId: 'u5',
    tenantName: 'Sara Getachew',
    monthlyRent: 55000,
    advancePayment: 100000,
    startDate: '2025-05-01',
    endDate: '2027-04-30',
    status: 'rejected',
    createdAt: '2025-04-10',
    signedAt: '2025-04-15',
    utilities: ['All inclusive'],
    terminationReason: 'Advance payment exceeds 2-month limit',
  },
];

export const disputes: Dispute[] = [
  {
    id: 'd1',
    agreementId: 'a1',
    reporterId: 'u3',
    reporterName: 'Tigist Haile',
    reporterRole: 'tenant',
    respondentId: 'u2',
    respondentName: 'Abebe Kebede',
    violationType: 'illegal_rent_increase',
    title: 'Unauthorized rent increase demand',
    description: 'Landlord verbally demanded an additional 3,000 ETB per month outside the agreement terms, threatening eviction if not complied with.',
    evidence: ['voice_recording.mp3', 'text_messages.pdf'],
    status: 'under_review',
    priority: 'high',
    createdAt: '2025-06-01',
    updatedAt: '2025-06-05',
    assignedTo: 'u1',
  },
  {
    id: 'd2',
    agreementId: 'a2',
    reporterId: 'u5',
    reporterName: 'Sara Getachew',
    reporterRole: 'tenant',
    respondentId: 'u2',
    respondentName: 'Abebe Kebede',
    violationType: 'maintenance_neglect',
    title: 'Broken water heater not repaired for 2 months',
    description: 'The water heater broke down in April and despite multiple requests, the landlord has not arranged repairs.',
    evidence: ['photos.zip', 'maintenance_request_emails.pdf'],
    status: 'open',
    priority: 'medium',
    createdAt: '2025-06-10',
    updatedAt: '2025-06-10',
  },
  {
    id: 'd3',
    agreementId: 'a3',
    reporterId: 'u9',
    reporterName: 'Meron Tadesse',
    reporterRole: 'tenant',
    respondentId: 'u2',
    respondentName: 'Abebe Kebede',
    violationType: 'wrongful_eviction',
    title: 'Eviction notice without legal basis',
    description: 'Received a 15-day eviction notice despite having an active 2-year lease with 20 months remaining.',
    evidence: ['eviction_notice.pdf', 'agreement_copy.pdf'],
    status: 'mediation',
    priority: 'critical',
    createdAt: '2025-05-20',
    updatedAt: '2025-06-08',
    assignedTo: 'u10',
  },
  {
    id: 'd4',
    agreementId: 'a1',
    reporterId: 'u2',
    reporterName: 'Abebe Kebede',
    reporterRole: 'landlord',
    respondentId: 'u3',
    respondentName: 'Tigist Haile',
    violationType: 'lease_violation',
    title: 'Subletting without permission',
    description: 'Tenant has subleted one room to another person without consent or notification.',
    evidence: ['witness_statement.pdf'],
    status: 'resolved',
    priority: 'medium',
    createdAt: '2025-04-15',
    updatedAt: '2025-05-10',
    resolvedAt: '2025-05-10',
    resolution: 'Tenant agreed to end subletting arrangement within 30 days. Written warning issued.',
    assignedTo: 'u1',
  },
  {
    id: 'd5',
    agreementId: 'a2',
    reporterId: 'u5',
    reporterName: 'Sara Getachew',
    reporterRole: 'tenant',
    respondentId: 'u2',
    respondentName: 'Abebe Kebede',
    violationType: 'deposit_withholding',
    title: 'Refusal to return security deposit from previous unit',
    description: 'Landlord refuses to return the security deposit from a previous agreement, claiming damages that do not exist.',
    evidence: ['move_out_photos.zip', 'deposit_receipt.pdf'],
    status: 'escalated',
    priority: 'high',
    createdAt: '2025-05-05',
    updatedAt: '2025-06-12',
    assignedTo: 'u10',
  },
];

export const rentAdjustments: RentAdjustment[] = [
  {
    id: 'ra1',
    agreementId: 'a1',
    propertyTitle: 'Modern 2BR Apartment in Bole',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    tenantName: 'Tigist Haile',
    currentRent: 15000,
    proposedRent: 16050,
    increasePercentage: 7,
    maxAllowedPercentage: 7,
    reason: 'Annual adjustment as per pricing strategy. Increased maintenance costs and inflation.',
    status: 'pending',
    createdAt: '2025-06-01',
  },
  {
    id: 'ra2',
    agreementId: 'a2',
    propertyTitle: 'Studio Condominium in Kirkos',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    tenantName: 'Sara Getachew',
    currentRent: 8000,
    proposedRent: 8400,
    increasePercentage: 5,
    maxAllowedPercentage: 7,
    reason: 'Annual cost-of-living adjustment.',
    status: 'approved',
    createdAt: '2025-05-15',
    reviewedAt: '2025-05-25',
    reviewedBy: 'u1',
    reviewNotes: 'Within allowable limit. Approved.',
  },
  {
    id: 'ra3',
    agreementId: 'a3',
    propertyTitle: '3BR House in Gullele',
    landlordId: 'u2',
    landlordName: 'Abebe Kebede',
    tenantName: 'Meron Tadesse',
    currentRent: 18000,
    proposedRent: 21600,
    increasePercentage: 20,
    maxAllowedPercentage: 7,
    reason: 'Market rate adjustment due to neighborhood development.',
    status: 'rejected',
    createdAt: '2025-05-01',
    reviewedAt: '2025-05-12',
    reviewedBy: 'u1',
    reviewNotes: 'Exceeds maximum allowed annual increase of 7%. Request denied.',
  },
  {
    id: 'ra4',
    agreementId: 'a1',
    propertyTitle: 'Modern 2BR Apartment in Bole',
    landlordId: 'u4',
    landlordName: 'Dawit Tadesse',
    tenantName: 'Helen Worku',
    currentRent: 25000,
    proposedRent: 26500,
    increasePercentage: 6,
    maxAllowedPercentage: 7,
    reason: 'Property improvements and rising utility costs.',
    status: 'under_review',
    createdAt: '2025-06-10',
  },
];

export const pricingStrategies: PricingStrategy[] = [
  {
    id: 'ps1',
    title: 'Addis Ababa 2025 Residential Rental Pricing Framework',
    description: 'City-wide rental pricing strategy establishing maximum rent thresholds and annual adjustment limits for all sub-cities.',
    maxAnnualIncreasePercent: 7,
    effectiveFrom: '2025-01-01',
    effectiveTo: '2025-12-31',
    subCityRules: [
      { subCity: 'Bole', maxRentPerSqm: 250, adjustmentFactor: 1.15 },
      { subCity: 'Kirkos', maxRentPerSqm: 220, adjustmentFactor: 1.1 },
      { subCity: 'Yeka', maxRentPerSqm: 200, adjustmentFactor: 1.05 },
      { subCity: 'Arada', maxRentPerSqm: 180, adjustmentFactor: 1.0 },
      { subCity: 'Lideta', maxRentPerSqm: 170, adjustmentFactor: 0.95 },
      { subCity: 'Gullele', maxRentPerSqm: 160, adjustmentFactor: 0.9 },
      { subCity: 'Nifas Silk-Lafto', maxRentPerSqm: 175, adjustmentFactor: 0.95 },
      { subCity: 'Addis Ketema', maxRentPerSqm: 150, adjustmentFactor: 0.85 },
      { subCity: 'Kolfe Keranio', maxRentPerSqm: 140, adjustmentFactor: 0.8 },
      { subCity: 'Akaky Kaliti', maxRentPerSqm: 120, adjustmentFactor: 0.75 },
      { subCity: 'Lemi Kura', maxRentPerSqm: 190, adjustmentFactor: 1.0 },
    ],
    status: 'published',
    createdAt: '2024-12-15',
    publishedAt: '2024-12-28',
  },
  {
    id: 'ps2',
    title: 'Addis Ababa 2026 Draft Pricing Strategy',
    description: 'Proposed pricing adjustments for 2026 based on market analysis and inflation data.',
    maxAnnualIncreasePercent: 8,
    effectiveFrom: '2026-01-01',
    effectiveTo: '2026-12-31',
    subCityRules: [
      { subCity: 'Bole', maxRentPerSqm: 270, adjustmentFactor: 1.2 },
      { subCity: 'Kirkos', maxRentPerSqm: 235, adjustmentFactor: 1.12 },
      { subCity: 'Yeka', maxRentPerSqm: 215, adjustmentFactor: 1.08 },
    ],
    status: 'draft',
    createdAt: '2025-06-01',
  },
];

export const notifications: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    title: 'New Dispute Filed',
    message: 'Tigist Haile has filed a complaint against Abebe Kebede for unauthorized rent increase.',
    type: 'warning',
    category: 'dispute',
    isRead: false,
    createdAt: '2025-06-01T10:30:00',
    link: '/dashboard/disputes',
  },
  {
    id: 'n2',
    userId: 'u1',
    title: 'Rent Adjustment Request',
    message: 'Abebe Kebede has submitted a rent adjustment request for Modern 2BR Apartment in Bole.',
    type: 'info',
    category: 'rent_adjustment',
    isRead: false,
    createdAt: '2025-06-01T09:15:00',
    link: '/dashboard/rent-adjustment',
  },
  {
    id: 'n3',
    userId: 'u1',
    title: 'Agreement Pending Verification',
    message: 'A new tenancy agreement between Bereket Solomon and Tigist Haile requires verification.',
    type: 'info',
    category: 'agreement',
    isRead: true,
    createdAt: '2025-06-01T08:00:00',
    link: '/dashboard/agreements',
  },
  {
    id: 'n4',
    userId: 'u1',
    title: 'Property Verification Needed',
    message: 'A new property "2BR Apartment in Nifas Silk" has been submitted for verification.',
    type: 'info',
    category: 'verification',
    isRead: true,
    createdAt: '2025-05-20T14:00:00',
    link: '/dashboard/admin/verifications',
  },
  {
    id: 'n5',
    userId: 'u1',
    title: 'Dispute Escalated',
    message: 'The deposit withholding case (D-005) has been escalated and requires immediate attention.',
    type: 'error',
    category: 'dispute',
    isRead: false,
    createdAt: '2025-06-12T11:45:00',
    link: '/dashboard/disputes',
  },
  {
    id: 'n6',
    userId: 'u1',
    title: 'Monthly Report Ready',
    message: 'The May 2025 rental market analytics report is ready for review.',
    type: 'success',
    category: 'system',
    isRead: true,
    createdAt: '2025-06-01T07:00:00',
    link: '/dashboard/analytics',
  },
];

export const rentPayments: RentPayment[] = [
  { id: 'pay1', agreementId: 'a1', propertyTitle: 'Modern 2BR Apartment in Bole', payerId: 'u3', payerName: 'Tigist Haile', recipientId: 'u2', recipientName: 'Abebe Kebede', amount: 15000, dueDate: '2025-06-01', paidDate: '2025-05-30', status: 'paid', method: 'cbe_birr', reference: 'CBE-20250530-001' },
  { id: 'pay2', agreementId: 'a2', propertyTitle: 'Studio Condominium in Kirkos', payerId: 'u5', payerName: 'Sara Getachew', recipientId: 'u2', recipientName: 'Abebe Kebede', amount: 8000, dueDate: '2025-06-01', paidDate: '2025-06-01', status: 'paid', method: 'telebirr', reference: 'TB-20250601-042' },
  { id: 'pay3', agreementId: 'a3', propertyTitle: '3BR House in Gullele', payerId: 'u9', payerName: 'Meron Tadesse', recipientId: 'u2', recipientName: 'Abebe Kebede', amount: 18000, dueDate: '2025-06-15', status: 'pending' },
  { id: 'pay4', agreementId: 'a1', propertyTitle: 'Modern 2BR Apartment in Bole', payerId: 'u3', payerName: 'Tigist Haile', recipientId: 'u2', recipientName: 'Abebe Kebede', amount: 15000, dueDate: '2025-07-01', status: 'pending' },
  { id: 'pay5', agreementId: 'a2', propertyTitle: 'Studio Condominium in Kirkos', payerId: 'u5', payerName: 'Sara Getachew', recipientId: 'u2', recipientName: 'Abebe Kebede', amount: 8000, dueDate: '2025-07-01', status: 'overdue' },
  { id: 'pay6', agreementId: 'a1', propertyTitle: 'Modern 2BR Apartment in Bole', payerId: 'u3', payerName: 'Tigist Haile', recipientId: 'u2', recipientName: 'Abebe Kebede', amount: 15000, dueDate: '2025-05-01', paidDate: '2025-05-01', status: 'paid', method: 'telebirr', reference: 'TB-20250501-007' },
  { id: 'pay7', agreementId: 'a3', propertyTitle: '3BR House in Gullele', payerId: 'u9', payerName: 'Meron Tadesse', recipientId: 'u2', recipientName: 'Abebe Kebede', amount: 18000, dueDate: '2025-05-15', paidDate: '2025-05-14', status: 'paid', method: 'cbe_birr', reference: 'CBE-20250514-003' },
];

export const supportingDocuments: SupportingDocument[] = [
  { id: 'doc1', uploaderId: 'u3', uploaderName: 'Tigist Haile', relatedEntityType: 'agreement', relatedEntityId: 'a1', relatedEntityTitle: 'Modern 2BR Apartment in Bole', fileName: 'kebele_id_front.pdf', fileType: 'pdf', fileSize: 245000, uploadedAt: '2025-02-20', description: 'Kebele ID front side' },
  { id: 'doc2', uploaderId: 'u3', uploaderName: 'Tigist Haile', relatedEntityType: 'dispute', relatedEntityId: 'd1', relatedEntityTitle: 'Unauthorized rent increase demand', fileName: 'text_messages_proof.pdf', fileType: 'pdf', fileSize: 512000, uploadedAt: '2025-06-01', description: 'Screenshots of threatening messages' },
  { id: 'doc3', uploaderId: 'u2', uploaderName: 'Abebe Kebede', relatedEntityType: 'property', relatedEntityId: 'p1', relatedEntityTitle: 'Modern 2BR Apartment in Bole', fileName: 'ownership_certificate.pdf', fileType: 'pdf', fileSize: 1024000, uploadedAt: '2025-02-15', description: 'Property ownership certificate' },
  { id: 'doc4', uploaderId: 'u5', uploaderName: 'Sara Getachew', relatedEntityType: 'dispute', relatedEntityId: 'd2', relatedEntityTitle: 'Broken water heater not repaired', fileName: 'photos_damage.zip', fileType: 'zip', fileSize: 3450000, uploadedAt: '2025-06-10', description: 'Photos of broken water heater' },
  { id: 'doc5', uploaderId: 'u2', uploaderName: 'Abebe Kebede', relatedEntityType: 'rent_adjustment', relatedEntityId: 'ra1', relatedEntityTitle: 'Rent adjustment for Bole apartment', fileName: 'maintenance_receipts.pdf', fileType: 'pdf', fileSize: 780000, uploadedAt: '2025-06-01', description: 'Maintenance cost receipts' },
  { id: 'doc6', uploaderId: 'u4', uploaderName: 'Dawit Tadesse', relatedEntityType: 'property', relatedEntityId: 'p2', relatedEntityTitle: 'Spacious 3BR House in Yeka', fileName: 'house_title_deed.pdf', fileType: 'pdf', fileSize: 920000, uploadedAt: '2025-03-10', description: 'Title deed for Yeka house' },
];

export const auditLogs: AuditLog[] = [
  { id: 'al1', userId: 'u1', userName: 'Yohannes Mesay', userRole: 'admin', action: 'UPDATE', entity: 'User', entityId: 'u7', details: 'Verified user account for Helen Worku', ipAddress: '192.168.1.10', timestamp: '2025-06-12T14:30:00' },
  { id: 'al2', userId: 'u6', userName: 'Mulugeta Assefa', userRole: 'dara_agent', action: 'APPROVE', entity: 'Agreement', entityId: 'a1', details: 'Verified tenancy agreement for Bole apartment', ipAddress: '10.0.0.45', timestamp: '2025-02-28T09:15:00' },
  { id: 'al3', userId: 'u1', userName: 'Yohannes Mesay', userRole: 'admin', action: 'REJECT', entity: 'RentAdjustment', entityId: 'ra3', details: 'Rejected rent adjustment - exceeds 7% annual limit', ipAddress: '192.168.1.10', timestamp: '2025-05-12T11:00:00' },
  { id: 'al4', userId: 'u10', userName: 'Kidist Alemu', userRole: 'admin', action: 'CREATE', entity: 'PricingStrategy', entityId: 'ps1', details: 'Published 2025 pricing strategy framework', ipAddress: '10.0.0.20', timestamp: '2024-12-28T08:00:00' },
  { id: 'al5', userId: 'u2', userName: 'Abebe Kebede', userRole: 'landlord', action: 'CREATE', entity: 'Property', entityId: 'p1', details: 'Registered new property in Bole', ipAddress: '172.16.0.5', timestamp: '2025-02-15T10:00:00' },
  { id: 'al6', userId: 'u3', userName: 'Tigist Haile', userRole: 'tenant', action: 'CREATE', entity: 'Dispute', entityId: 'd1', details: 'Filed complaint for unauthorized rent increase', ipAddress: '172.16.0.12', timestamp: '2025-06-01T10:30:00' },
  { id: 'al7', userId: 'u1', userName: 'Yohannes Mesay', userRole: 'admin', action: 'UPDATE', entity: 'SystemParameter', entityId: 'sp1', details: 'Updated max advance payment months from 3 to 2', ipAddress: '192.168.1.10', timestamp: '2025-01-15T16:00:00' },
  { id: 'al8', userId: 'u6', userName: 'Mulugeta Assefa', userRole: 'dara_agent', action: 'APPROVE', entity: 'Property', entityId: 'p4', details: 'Verified property ownership documents', ipAddress: '10.0.0.45', timestamp: '2025-04-10T13:45:00' },
];

export const penaltyNotices: PenaltyNotice[] = [
  { id: 'pn1', issuedTo: 'u2', issuedToName: 'Abebe Kebede', issuedBy: 'u6', issuedByName: 'Mulugeta Assefa', disputeId: 'd1', type: 'warning', reason: 'Unauthorized rent increase demand on tenant Tigist Haile. First formal warning issued.', status: 'issued', issuedAt: '2025-06-05' },
  { id: 'pn2', issuedTo: 'u2', issuedToName: 'Abebe Kebede', issuedBy: 'u6', issuedByName: 'Mulugeta Assefa', disputeId: 'd3', type: 'fine', reason: 'Attempted wrongful eviction of tenant Meron Tadesse. Fine imposed as per proclamation.', amount: 25000, status: 'acknowledged', issuedAt: '2025-06-08', deadline: '2025-07-08' },
  { id: 'pn3', issuedTo: 'u2', issuedToName: 'Abebe Kebede', issuedBy: 'u1', issuedByName: 'Yohannes Mesay', disputeId: 'd5', type: 'legal_action', reason: 'Repeated deposit withholding complaints. Case referred for legal proceedings.', status: 'enforced', issuedAt: '2025-06-12' },
  { id: 'pn4', issuedTo: 'u3', issuedToName: 'Tigist Haile', issuedBy: 'u6', issuedByName: 'Mulugeta Assefa', disputeId: 'd4', agreementId: 'a1', type: 'warning', reason: 'Subletting without landlord permission. Formal warning issued.', status: 'acknowledged', issuedAt: '2025-05-10' },
];

export const systemParameters: SystemParameter[] = [
  { id: 'sp1', key: 'max_advance_months', label: 'Maximum Advance Payment (Months)', value: '2', category: 'rental', description: 'Maximum number of months a landlord can collect as advance payment', updatedAt: '2025-01-15', updatedBy: 'u1' },
  { id: 'sp2', key: 'min_lease_years', label: 'Minimum Lease Duration (Years)', value: '2', category: 'rental', description: 'Minimum lease duration in years as per the proclamation', updatedAt: '2025-01-15', updatedBy: 'u1' },
  { id: 'sp3', key: 'max_annual_increase', label: 'Maximum Annual Rent Increase (%)', value: '7', category: 'rental', description: 'Maximum percentage a landlord can increase rent annually', updatedAt: '2025-01-15', updatedBy: 'u1' },
  { id: 'sp4', key: 'dispute_review_days', label: 'Dispute Review Period (Days)', value: '30', category: 'compliance', description: 'Maximum days allowed for initial dispute review', updatedAt: '2025-01-15', updatedBy: 'u1' },
  { id: 'sp5', key: 'eviction_notice_days', label: 'Eviction Notice Period (Days)', value: '90', category: 'compliance', description: 'Minimum days of notice required before eviction', updatedAt: '2025-01-15', updatedBy: 'u1' },
  { id: 'sp6', key: 'verification_sla_days', label: 'Verification SLA (Days)', value: '5', category: 'system', description: 'Target days for completing property/agreement verification', updatedAt: '2025-03-01', updatedBy: 'u1' },
  { id: 'sp7', key: 'session_timeout_mins', label: 'Session Timeout (Minutes)', value: '30', category: 'system', description: 'User session timeout duration in minutes', updatedAt: '2025-01-15', updatedBy: 'u1' },
  { id: 'sp8', key: 'payment_reminder_days', label: 'Payment Reminder (Days Before)', value: '5', category: 'notification', description: 'Days before due date to send payment reminder', updatedAt: '2025-02-10', updatedBy: 'u1' },
  { id: 'sp9', key: 'agreement_expiry_alert_days', label: 'Agreement Expiry Alert (Days)', value: '60', category: 'notification', description: 'Days before agreement expiry to send alert', updatedAt: '2025-02-10', updatedBy: 'u1' },
];

export const analyticsData: AnalyticsData = {
  rentalTrends: [
    { month: 'Jan', averageRent: 14200, agreements: 45 },
    { month: 'Feb', averageRent: 14500, agreements: 52 },
    { month: 'Mar', averageRent: 14800, agreements: 68 },
    { month: 'Apr', averageRent: 15100, agreements: 61 },
    { month: 'May', averageRent: 15400, agreements: 73 },
    { month: 'Jun', averageRent: 15700, agreements: 58 },
    { month: 'Jul', averageRent: 15900, agreements: 42 },
    { month: 'Aug', averageRent: 16100, agreements: 55 },
    { month: 'Sep', averageRent: 16300, agreements: 67 },
    { month: 'Oct', averageRent: 16500, agreements: 71 },
    { month: 'Nov', averageRent: 16800, agreements: 64 },
    { month: 'Dec', averageRent: 17000, agreements: 48 },
  ],
  propertyDistribution: [
    { subCity: 'Bole', count: 2450, avgRent: 28000 },
    { subCity: 'Kirkos', count: 1890, avgRent: 18500 },
    { subCity: 'Yeka', count: 2100, avgRent: 22000 },
    { subCity: 'Arada', count: 1650, avgRent: 15000 },
    { subCity: 'Lideta', count: 1420, avgRent: 12500 },
    { subCity: 'Gullele', count: 1180, avgRent: 14000 },
    { subCity: 'Nifas Silk-Lafto', count: 1750, avgRent: 16000 },
    { subCity: 'Addis Ketema', count: 980, avgRent: 10000 },
    { subCity: 'Kolfe Keranio', count: 1340, avgRent: 11000 },
    { subCity: 'Akaky Kaliti', count: 720, avgRent: 8500 },
    { subCity: 'Lemi Kura', count: 890, avgRent: 19000 },
  ],
  occupancyRates: [
    { subCity: 'Bole', rate: 94 },
    { subCity: 'Kirkos', rate: 91 },
    { subCity: 'Yeka', rate: 89 },
    { subCity: 'Arada', rate: 87 },
    { subCity: 'Lideta', rate: 85 },
    { subCity: 'Gullele', rate: 82 },
    { subCity: 'Nifas Silk-Lafto', rate: 88 },
    { subCity: 'Addis Ketema', rate: 80 },
    { subCity: 'Kolfe Keranio', rate: 78 },
    { subCity: 'Akaky Kaliti', rate: 72 },
    { subCity: 'Lemi Kura', rate: 90 },
  ],
  disputeStats: [
    { type: 'Illegal Rent Increase', count: 34 },
    { type: 'Wrongful Eviction', count: 22 },
    { type: 'Maintenance Neglect', count: 18 },
    { type: 'Deposit Withholding', count: 15 },
    { type: 'Harassment', count: 8 },
    { type: 'Lease Violation', count: 12 },
    { type: 'Other', count: 6 },
  ],
  revenueProjection: [
    { quarter: 'Q1 2025', projected: 720000000, actual: 685000000 },
    { quarter: 'Q2 2025', projected: 780000000, actual: 742000000 },
    { quarter: 'Q3 2025', projected: 840000000, actual: 0 },
    { quarter: 'Q4 2025', projected: 900000000, actual: 0 },
  ],
};
